class AppLocalizations {
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app_name': 'Nexus Edu',
      'dashboard': 'Dashboard',
      'shorts': 'Shorts',
      'tutor': 'Tutor',
      'notes': 'Notes',
      'profile': 'Profile',
      'focus_room': 'Focus Room',
      'study_rooms': 'Study Rooms',
      'parent_dashboard': 'Parent Dashboard',
      'settings': 'Settings',
      'search': 'Search',
      'generate': 'Generate',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'export': 'Export',
      'copy': 'Copy',
      'quiz': 'Quiz',
      'streak': 'Streak',
      'sessions': 'Sessions',
      'minutes': 'Minutes',
      'days_left': 'days left',
      'work_session': 'WORK SESSION',
      'break_time': 'BREAK TIME',
      'remaining': 'Remaining',
      'start': 'Start',
      'pause': 'Pause',
      'reset': 'Reset',
      'skip': 'Skip',
      'ready_to_excel': 'Ready to excel?',
      'your_ai_study_hub': 'Your AI Study Hub',
      'smart_learning': 'Smart Learning',
      'no_notes_yet': 'No notes yet',
      'create_first_note': 'Tap + to create your first note',
      'enter_topic': 'Enter a topic',
      'ask_nexus': 'Ask Nexus anything...',
      'welcome_back': 'Welcome back!',
      'keep_going': 'Keep going!',
      'amazing': 'Amazing!',
      'active': 'Active',
      'live': 'LIVE',
      'online': 'online',
      'joined': 'Joined',
      'invite': 'Invite',
      'create_room': 'Create Room',
      'voice_command': 'Voice Command',
      'listening': 'Listening...',
      'light_mode': 'Light',
      'dark_mode': 'Dark',
      'system_mode': 'System',
    },
    'hi': {
      'app_name': 'Nexus Edu',
      'dashboard': 'होम',
      'shorts': 'Shorts',
      'tutor': 'Tutor',
      'notes': 'Notes',
      'profile': 'Profile',
      'focus_room': 'Focus Room',
      'study_rooms': 'Study Rooms',
      'parent_dashboard': 'Parent Dashboard',
      'settings': 'Settings',
      'search': 'Search',
      'generate': 'Generate',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'export': 'Export',
      'copy': 'Copy',
      'quiz': 'Quiz',
      'streak': 'Streak',
      'sessions': 'Sessions',
      'minutes': 'Minutes',
      'days_left': 'days left',
      'work_session': 'WORK SESSION',
      'break_time': 'BREAK TIME',
      'remaining': 'Remaining',
      'start': 'Start',
      'pause': 'Pause',
      'reset': 'Reset',
      'skip': 'Skip',
      'ready_to_excel': 'Padhai karo!',
      'your_ai_study_hub': 'Aapka AI Study Hub',
      'smart_learning': 'Smart Learning',
      'no_notes_yet': 'Abhi koi notes nahi hai',
      'create_first_note': 'Apna pehla note banane ke liye + dabao',
      'enter_topic': 'Topic dalo',
      'ask_nexus': 'Nexus se kuch bhi pucho...',
      'welcome_back': 'Wapas aao!',
      'keep_going': 'Chalate raho!',
      'amazing': 'Zabardast!',
      'active': 'Active',
      'live': 'LIVE',
      'online': 'online',
      'joined': 'Joined',
      'invite': 'Invite',
      'create_room': 'Room banao',
      'voice_command': 'Voice Command',
      'listening': 'Sun raha hai...',
      'light_mode': 'Light',
      'dark_mode': 'Dark',
      'system_mode': 'System',
    },
    'hinglish': {
      'app_name': 'Nexus Edu',
      'dashboard': 'Home',
      'shorts': 'Shorts',
      'tutor': 'Tutor',
      'notes': 'Notes',
      'profile': 'Profile',
      'focus_room': 'Focus Room',
      'study_rooms': 'Study Rooms',
      'parent_dashboard': 'Parent Dashboard',
      'settings': 'Settings',
      'search': 'Search',
      'generate': 'Generate',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'export': 'Export',
      'copy': 'Copy',
      'quiz': 'Quiz',
      'streak': 'Streak',
      'sessions': 'Sessions',
      'minutes': 'Minutes',
      'days_left': 'days left',
      'work_session': 'WORK SESSION',
      'break_time': 'BREAK TIME',
      'remaining': 'Remaining',
      'start': 'Start',
      'pause': 'Pause',
      'reset': 'Reset',
      'skip': 'Skip',
      'ready_to_excel': 'Chalo padhte hain!',
      'your_ai_study_hub': 'Tumhara AI Study Hub',
      'smart_learning': 'Smart Learning',
      'no_notes_yet': 'Koi notes nahi abhi',
      'create_first_note': 'Pehla note banane ke liye + dabao',
      'enter_topic': 'Topic batao',
      'ask_nexus': 'Nexus se pucho kuch bhi...',
      'welcome_back': 'Wapas aao!',
      'keep_going': 'Aage badho!',
      'amazing': 'Bahut badiya!',
      'active': 'Active',
      'live': 'LIVE',
      'online': 'online',
      'joined': 'Joined',
      'invite': 'Invite',
      'create_room': 'Room banao',
      'voice_command': 'Voice Command',
      'listening': 'Sun raha hai...',
      'light_mode': 'Light',
      'dark_mode': 'Dark',
      'system_mode': 'System',
    },
  };

  static String translate(String key, String language) {
    return _translations[language]?[key] ?? _translations['en']?[key] ?? key;
  }

  static List<String> get supportedLanguages => ['en', 'hi', 'hinglish'];

  static String languageName(String code) {
    switch (code) {
      case 'en': return 'English';
      case 'hi': return 'हिन्दी';
      case 'hinglish': return 'Hinglish';
      default: return 'English';
    }
  }
}
